version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "3000:80"
    networks:
      - backend
    depends_on:
      - user
      - room
      - device
      - action

  mosquitto:
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend
    environment:
      - PUID=1883
      - PGID=1883

  smarthome-db:
    image: "destmaxi/kv-storage-system:latest"
    ports:
      - "5984:5984"
    networks:
      - backend

  user:
    image: destmaxi/user:latest
    environment:
      - NODE_ENV=development
      - DB_URL=http://admin:admin@smarthome-db:5984/users
    networks:
      - backend
    restart: on-failure
    depends_on:
      - smarthome-db

  action:
    build: ./action
    volumes:
      - ./action:/usr/src/action-service
      - ./boot-in-order.sh:/usr/src/action-service/boot-in-order.sh
      - ./func_to_string.js:/usr/src/action-service/func_to_string.js
      - ./gulpfile.js:/usr/src/action-service/gulpfile.js
      - ./daemon.js:/usr/src/action-service/src/daemon.js
      - /usr/src/action-service/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
    restart: on-failure

  device:
    build: ./device
    volumes:
      - ./device:/usr/src/device-service
      - ./boot-in-order.sh:/usr/src/device-service/boot-in-order.sh
      - ./func_to_string.js:/usr/src/device-service/func_to_string.js
      - ./gulpfile.js:/usr/src/device-service/gulpfile.js
      - ./daemon.js:/usr/src/device-service/src/daemon.js
      - ./permissions.js:/usr/src/device-service/src/utils/permissions.js
      - /usr/src/device-service/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
    restart: on-failure
    depends_on:
      - smarthome-db

  room:
    build: ./room
    volumes:
      - ./room:/usr/src/room-service
      - ./boot-in-order.sh:/usr/src/room-service/boot-in-order.sh
      - ./func_to_string.js:/usr/src/room-service/func_to_string.js
      - ./gulpfile.js:/usr/src/room-service/gulpfile.js
      - ./daemon.js:/usr/src/room-service/src/daemon.js
      - ./permissions.js:/usr/src/room-service/src/utils/permissions.js
      - /usr/src/room-service/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
    restart: on-failure
    depends_on:
      - smarthome-db

networks:
  backend:
    driver: overlay
