version: "3"
services:
  mosquitto:
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend
    environment:
      - PUID=1883
      - PGID=1883

  smarthome-db:
    image: "destmaxi/kv-storage-system:latest"
    ports:
      - "3000:5984"
    networks:
      - backend

  user:
    build: ./user
    ports:
      - "3080:3080"
    volumes:
      - ./user:/usr/src/user-service
      - ./boot-in-order.sh:/usr/src/user-service/boot-in-order.sh
      - ./gulpfile.js:/usr/src/user-service/gulpfile.js
      - ./daemon.js:/usr/src/user-service/src/daemon.js
      - /usr/src/user-service/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
    restart: on-failure
    depends_on:
      - smarthome-db

  device:
    build: ./device
    ports:
      - "3082:3082"
    volumes:
      - ./device:/usr/src/device-service
      - ./boot-in-order.sh:/usr/src/device-service/boot-in-order.sh
      - ./gulpfile.js:/usr/src/device-service/gulpfile.js
      - ./daemon.js:/usr/src/device-service/src/daemon.js
      - /usr/src/device-service/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
    restart: on-failure
    depends_on:
      - smarthome-db

  room:
    build: ./room
    ports:
      - "3081:3081"
    volumes:
      - ./room:/usr/src/room-service
      - ./boot-in-order.sh:/usr/src/room-service/boot-in-order.sh
      - ./func_to_string.js:/usr/src/room-service/func_to_string.js
      - ./gulpfile.js:/usr/src/room-service/gulpfile.js
      - ./daemon.js:/usr/src/room-service/src/daemon.js
      - /usr/src/room-service/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend
    restart: on-failure
    depends_on:
      - smarthome-db

networks:
  backend:
    driver: overlay
